name: 'Run action from different repo'
on:
  push:
    branches:
      - main
jobs:
  run-action1:
    name: Run Action 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lisadean/actions-monorepo-demo
          token: ${{ secrets.PRIVATE_REPO_ACCESS }}
      - run: echo $(ls -la)
      - uses: lisadean/actions-monorepo-demo/action1@main
  # run-action2:
  #   name: Run Action 2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lisadean/actions-monorepo-demo/action2@main
