name: 'Run action from different repo'
on:
  push:
    branches:
      - main
jobs:
  run-action1:
    name: Run Action 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lisadean/actions-monorepo-demo
          token: ${{ secrets.PRIVATE_REPO_ACCESS }}
          path: ./actions-monorepo-demo
      - run: |
          pwd
          ls -la
          cd actions-monorepo-demo
          pwd
          ls -la
          cd ..
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: ./actions-monorepo-demo/action1@main
  test-directory-location:
    name: Test directory location
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lisadean/actions-monorepo-demo
          token: ${{ secrets.PRIVATE_REPO_ACCESS }}
          path: ./actions-monorepo-demo
      - run: |
          pwd
          ls -la
          cd actions-monorepo-demo
          pwd
          ls -la
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -la
  # run-action2:
  #   name: Run Action 2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lisadean/actions-monorepo-demo/action2@main
